ALTER TABLE "economic_profiles"
  ADD COLUMN IF NOT EXISTS "consistencyScore"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "growthScore"         DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "participationScore"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "activityLevel"       DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "riskLevel"           TEXT NOT NULL DEFAULT 'Very High';
